#!/bin/sh
#
# A hook to change dev environments based on branch.
#

# Variables.
dbUser=root
dbPass=root
dbPrefix=hrmeta_
# User to give access to.
dbUserAccess=hrmeta_main

# Don't change anything below this line.
# ____________________________________

# Get parameters.
prevHEAD=$1
newHEAD=$2
checkoutType=$3

# Get branches.
# Hardcoding previous branch as master.
prevBranch=master
currentBranch=`git rev-parse --abbrev-ref HEAD`

echo Previous branch: $prevBranch \(hardcoded\)
echo Current branch: $currentBranch

# If db does not exist, create it.
if ! `mysql -u $dbUser -p$dbPass -e 'USE $dbPrefix$currentBranch'`; then
	currentTimestamp=$(date +%s)

	echo "DB does not exist. Trying to create it."
	mysql -u $dbUser -p$dbPass -e 'CREATE DATABASE $dbPrefix$currentBranch'

	# Copy from current branch db.
	mysqldump -u $dbUser -p$dbPass $dbPrefix$prevBranch > $currentTimestamp.sql
	mysql -u $dbUser -p$dbPass $dbPrefix$currentBranch < $currentTimestamp.sql
	rm $currentTimestamp.sql

	# Grant privileges.
	mysql -u $dbUser -p$dbPass -e 'GRANT ALL PRIVILEGES ON $dbPrefix$currentBranch.* TO '$dbUserAccess'@'localhost' WITH GRANT OPTION;'
fi

# Change DB in settings file.
# Variables.
settingsFolder=sites/default
sfPrevString=$dbPrefix$prevBranch
sfNewString=$dbPrefix$currentBranch

cd sites/default
# Check file exists.
if [ ! -f "settings.php" ]; then
	echo 'settings.php file not found!'
else
	# Check if backup for master branch exists.
	if [ ! -f "settings_master.php" ]; then
		cp settings.php settings_master.php
		chmod 644 settings_master.php
	fi

	# Check if settings file for current branch exists.
	if [ ! -f "settings_$currentBranch.php" -a "$currentBranch" != "master" ]; then
		sed s/$sfPrevString/$sfNewString/g settings_master.php > settings_$currentBranch.php
		chmod 644 settings_$currentBranch.php
	fi

	# Swap files.
	chmod 644 settings.php
	rm settings.php
	cp settings_$currentBranch.php settings.php
fi
